import { ExternalLink } from 'lucide-react';
import { useMemo, useState } from 'react';
import { projects } from '../data';

export default function Portfolio() {
  const [filter, setFilter] = useState('All');
  const categories = useMemo(() => ['All', ...new Set(projects.map((project) => project.category))], []);
  const visible = filter === 'All' ? projects : projects.filter((project) => project.category === filter);
  return <div className="site-shell"><section className="site-container py-16 sm:py-20"><div className="max-w-2xl"><p className="section-label mb-4">Selected projects</p><h1 className="text-4xl font-extrabold tracking-[-0.035em] text-balance sm:text-6xl">Digital work built for real-world complexity.</h1><p className="mt-6 text-lg leading-8 text-[#5f7590] dark:text-[#93a9c0]">A collection of web, spatial, and mobile systems, designed around performance and practical use.</p></div><div className="mt-10 flex flex-wrap gap-2">{categories.map((category) => <button key={category} onClick={() => setFilter(category)} aria-pressed={filter === category} className={filter === category ? 'rounded-lg bg-[#3e7bc1] px-3.5 py-2 text-sm font-bold text-white' : 'rounded-lg border border-[#dbe6f2] bg-white px-3.5 py-2 text-sm font-bold text-[#5f7590] hover:border-[#3e7bc1] dark:border-[#23384b] dark:bg-[#121e2c] dark:text-[#93a9c0]'}>{category}</button>)}</div><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{visible.map((project) => <article key={project.title} className="surface group flex overflow-hidden rounded-2xl flex-col"><div className="aspect-[16/10] overflow-hidden bg-[#eaf1f9] dark:bg-[#182838]"><img src={project.image} alt={project.title} className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-[1.03]" /></div><div className="flex flex-1 flex-col p-5"><div className="flex items-center justify-between gap-4"><p className="text-xs font-bold uppercase tracking-[0.12em] text-[#3e7bc1] dark:text-[#7eaee0]">{project.category}</p><ExternalLink size={16} className="text-[#5f7590]" /></div><h2 className="mt-3 text-xl font-bold leading-7">{project.title}</h2><p className="mt-3 text-sm leading-6 text-[#5f7590] dark:text-[#93a9c0]">{project.description}</p><div className="mt-5 flex flex-wrap gap-1.5">{project.tags.map((tag) => <span key={tag} className="rounded-md bg-[#eaf1f9] px-2 py-1 text-xs font-semibold text-[#5f7590] dark:bg-[#182838] dark:text-[#93a9c0]">{tag}</span>)}</div></div></article>)}</div></section></div>;
}
