import { Menu, Moon, Sun, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { NavLink } from 'react-router';
import { personal } from '../data';
import { cn } from '../lib/utils';
import { usePreferences } from '../lib/preferences';

export default function Navbar() {
  const [open, setOpen] = useState(false); const [scrolled, setScrolled] = useState(false);
  const { locale, setLocale, dark, setDark } = usePreferences();
  const id = locale === 'id';
  const navLinks = [{ name: id ? 'Tentang' : 'About', path: '/about' }, { name: id ? 'Proyek' : 'Projects', path: '/portfolio' }, { name: id ? 'Tulisan' : 'Writing', path: '/blog' }];
  useEffect(() => { const handler = () => setScrolled(window.scrollY > 12); window.addEventListener('scroll', handler); return () => window.removeEventListener('scroll', handler); }, []);
  const linkClass = ({ isActive }: { isActive: boolean }) => cn('text-sm font-semibold transition-colors', isActive ? 'text-[#3e7bc1] dark:text-[#7eaee0]' : 'text-[#5f7590] hover:text-[#16283d] dark:text-[#93a9c0] dark:hover:text-white');
  return <header className={cn('fixed inset-x-0 top-0 z-50 border-b transition-colors', scrolled ? 'border-[#dbe6f2] bg-[#f4f8fc]/95 backdrop-blur-md dark:border-[#23384b] dark:bg-[#0c1521]/95' : 'border-transparent bg-[#f4f8fc]/70 dark:bg-[#0c1521]/70')}><div className="site-container flex h-20 items-center justify-between"><NavLink to="/" className="flex items-center gap-2.5"><span className="grid h-9 w-9 place-items-center rounded-[11px] bg-[#3e7bc1] text-sm font-extrabold text-white">MA</span><span className="text-sm font-bold tracking-[-0.01em]">{personal.name}</span></NavLink><nav className="hidden items-center gap-5 md:flex">{navLinks.map((link) => <NavLink key={link.path} to={link.path} className={linkClass}>{link.name}</NavLink>)}<button onClick={() => setLocale(id ? 'en' : 'id')} className="rounded-lg border border-[#dbe6f2] bg-white px-2.5 py-2 text-xs font-extrabold text-[#5f7590] dark:border-[#23384b] dark:bg-[#121e2c] dark:text-[#93a9c0]" aria-label="Change language">{id ? 'EN' : 'ID'}</button><button onClick={() => setDark(!dark)} className="grid h-9 w-9 place-items-center rounded-lg border border-[#dbe6f2] bg-white text-[#5f7590] dark:border-[#23384b] dark:bg-[#121e2c] dark:text-[#93a9c0]" aria-label={dark ? 'Use light mode' : 'Use dark mode'}>{dark ? <Sun size={16} /> : <Moon size={16} />}</button><NavLink to="/contact" className="rounded-xl bg-[#3e7bc1] px-4 py-2.5 text-sm font-bold text-white transition-colors hover:bg-[#3269a7]">{id ? 'Hubungi' : 'Hire me'}</NavLink></nav><div className="flex items-center gap-1.5 md:hidden"><button onClick={() => setDark(!dark)} className="grid h-9 w-9 place-items-center rounded-lg border border-[#dbe6f2] bg-white text-[#5f7590] dark:border-[#23384b] dark:bg-[#121e2c] dark:text-[#93a9c0]" aria-label={dark ? 'Use light mode' : 'Use dark mode'}>{dark ? <Sun size={16} /> : <Moon size={16} />}</button><button onClick={() => setOpen(!open)} className="rounded-lg p-2" aria-expanded={open} aria-label="Toggle navigation">{open ? <X /> : <Menu />}</button></div></div>{open && <nav className="site-container grid border-t border-[#dbe6f2] pb-5 pt-3 dark:border-[#23384b] md:hidden"><button onClick={() => setLocale(id ? 'en' : 'id')} className="border-b border-[#dbe6f2] py-4 text-left text-sm font-bold dark:border-[#23384b]">{id ? 'English' : 'Bahasa Indonesia'}</button>{navLinks.map((link) => <NavLink key={link.path} to={link.path} onClick={() => setOpen(false)} className="border-b border-[#dbe6f2] py-4 text-lg font-bold dark:border-[#23384b]">{link.name}</NavLink>)}<NavLink to="/contact" onClick={() => setOpen(false)} className="mt-4 rounded-xl bg-[#3e7bc1] px-4 py-3 text-center text-sm font-bold text-white">{id ? 'Hubungi' : 'Hire me'}</NavLink></nav>}</header>;
}
